# Generated by Django 5.1.3 on 2024-11-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('average_rating', models.FloatField()),
                ('isbn', models.IntegerField()),
                ('isbn13', models.IntegerField()),
                ('language_code', models.CharField(max_length=200)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('text_reviews_count', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.IntegerField(primary_key=True, serialize=False)),
                ('return_date', models.DateField()),
                ('debt', models.FloatField()),
            ],
        ),
    ]
