# Generated by Django 5.1.3 on 2024-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.CharField(max_length=200),
        ),
    ]
