# Generated by Django 5.1.3 on 2024-11-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_books_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('memberid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('return_date', models.CharField(blank=True, max_length=200)),
                ('debt', models.FloatField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
