# Generated by Django 5.1.3 on 2024-11-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_members_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
